### ISSUE TITLE
0: Empty list of items given to `MultiSelect`

### ISSUE THREAD

**Issue by bryceprutsos** [Supergamer1337/media-cleaner#7]
Getting error 

`Error:
   0: Empty list of items given to MultiSelect

Location:
   src\main.rs:30

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.`

![image](https://user-images.githubusercontent.com/74235158/224572822-1f9d9435-55a1-4ada-837a-e59c6951c492.png)

![image](https://user-images.githubusercontent.com/74235158/224572781-ebf866ac-e399-41fb-9033-39c177e9d246.png)

**Comment by Krysset** [comment]
I have the same problem!

**Comment by Supergamer1337** [comment]
The issue here is that your overseerr instance either didn't return any valid requests to check, or there was a failure to get the appropriate data from one or multiple of the other services. This should probably have a more user friendly error, but without knowing exactly what came back from the different responses there's really nothing I can do. I am in the middle of improving error handling, as I've realized that there are *a lot* of cases I've not yet covered. So there should be an update that will help with further diagnosing this problem.

**Comment by Supergamer1337** [comment]
Just released a new version of the application that should give you more information when an error occurs. Could you try it and report back?

**Comment by bryceprutsos** [comment]
hi @Supergamer1337, I have downloaded the new version and have updated my Tautulli to latest version errors below
Error 4 was Got 404 Not Found from Tautulli. Please create issue on Github. Dependent API seems to have changed.
-----------------------------------------------------------------------------
Error 5 was error decoding response body: expected value at line 1 column 1

![image](https://user-images.githubusercontent.com/74235158/224857337-9305440f-26bd-45fa-a833-f7ca052e0b56.png)

**Comment by Supergamer1337** [comment]
Could you try to remove the / at the end of your urls?

**Comment by Supergamer1337** [comment]
This should have been fixed as of v1.0.0, could you try that version and report back?

**Comment by bryceprutsos** [comment]
I took off the / at the end of the URLs and it works now.

Thank you very much.

I additional question I had was whether there was a way to sort its findings such as sorting by most space.  This would help out users that have a large amount of different series.

**Comment by Supergamer1337** [comment]
Issue marked as resolved, and your request has been moved to #8
